# Generated by Django 2.1.4 on 2018-12-29 03:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20181228_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='account_opened',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 28, 21, 1, 32, 91509)),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL),
        ),
    ]
