# Generated by Django 2.1.4 on 2018-12-29 01:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20181228_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='account_opened',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 28, 19, 57, 26, 924881)),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
